import { prisma } from '../src/lib/prisma';

const departments = [
  {
    id: 1,
    isActive: false,
    title: 'Dph',
    weekdays: [1, 4],
  },
  {
    id: 2,
    isActive: false,
    title: 'Bebidas',
    weekdays: [1],
  },
  {
    id: 3,
    isActive: false,
    title: 'Perecíveis',
    weekdays: [3],
  },
  {
    id: 4,
    isActive: false,
    title: 'Seca Doce',
    weekdays: [5],
  },
  {
    id: 5,
    isActive: false,
    title: 'Seca Salgada',
    weekdays: [2],
  },
];

const streets = [
  {
    id: 1,
    isActive: false,
    code: 'LJA-01-A-000',
    title: 'Corredor 01 Lado A',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 3,
    isActive: false,
    code: 'ACG-01-A-000',
    title: 'Açougue',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 4,
    isActive: false,
    code: 'DEF-01-A-000',
    title: 'Defumados',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 5,
    isActive: false,
    code: 'FRZ-01-A-000',
    title: 'Freezer 01',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 6,
    isActive: false,
    code: 'FRZ-01-B-000',
    title: 'Freezer 02',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 7,
    isActive: false,
    code: 'ILH-01-A-000',
    title: 'Ilha Congelado 01',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 8,
    isActive: false,
    code: 'ILH-01-B-000',
    title: 'Ilha Congelado 02',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 9,
    isActive: false,
    code: 'ILH-01-C-000',
    title: 'Ilha Congelado 03',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 10,
    isActive: false,
    code: 'PAD-01-A-000',
    title: 'Padaria',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 11,
    isActive: false,
    code: 'SOR-01-A-000',
    title: 'Sorvetes',
    weekday: 3,
    departamentId: '3',
  },
  {
    id: 12,
    isActive: false,
    code: 'LJA-05-A-000',
    title: 'Corredor 05 Lado A',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 13,
    isActive: false,
    code: 'LJA-05-B-000',
    title: 'Corredor 05 Lado B',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 14,
    isActive: false,
    code: 'LJA-06-A-000',
    title: 'Corredor 06 Lado A',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 15,
    isActive: false,
    code: 'LJA-06-B-000',
    title: 'Corredor 06 Lado B',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 16,
    isActive: false,
    code: 'LJA-07-A-000',
    title: 'Corredor 07 Lado A',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 17,
    isActive: false,
    code: 'LJA-07-B-000',
    title: 'Corredor 07 Lado B',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 18,
    isActive: false,
    code: 'LJA-08-A-000',
    title: 'Corredor 08 Lado A',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 19,
    isActive: false,
    code: 'LJA-08-B-000',
    title: 'Corredor 08 Lado B',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 20,
    isActive: false,
    code: 'LJA-09-A-000',
    title: 'Corredor 09 Lado A',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 21,
    isActive: false,
    code: 'LJA-09-B-000',
    title: 'Corredor 09 Lado B',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 22,
    isActive: false,
    code: 'LJA-10-A-000',
    title: 'Corredor 10 Lado A',
    weekday: 1,
    departamentId: '1',
  },
  {
    id: 23,
    isActive: false,
    code: 'LJA-10-B-000',
    title: 'Corredor 10 Lado B',
    weekday: 1,
    departamentId: '1',
  },
  {
    id: 24,
    isActive: false,
    code: 'LJA-11-A-000',
    title: 'Corredor 11 Lado A',
    weekday: 1,
    departamentId: '1',
  },
  {
    id: 25,
    isActive: false,
    code: 'HAV-01-A-000',
    title: 'Havaianas',
    weekday: 4,
    departamentId: '1',
  },
  {
    id: 26,
    isActive: false,
    code: 'LJA-01-B-000',
    title: 'Corredor 01 Lado B',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 27,
    isActive: false,
    code: 'LJA-02-A-000',
    title: 'Corredor 02 Lado A',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 28,
    isActive: false,
    code: 'LJA-02-B-000',
    title: 'Corredor 02 Lado B',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 29,
    isActive: false,
    code: 'LJA-03-A-000',
    title: 'Corredor 03 Lado A',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 30,
    isActive: false,
    code: 'LJA-03-B-000',
    title: 'Corredor 03 Lado B',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 31,
    isActive: false,
    code: 'LJA-04-A-000',
    title: 'Corredor 04 Lado A',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 32,
    isActive: false,
    code: 'LJA-04-B-000',
    title: 'Corredor 04 Lado B',
    weekday: 1,
    departamentId: '2',
  },
  {
    id: 33,
    isActive: false,
    code: 'LJA-11-B-000',
    title: 'Corredor 11 Lado B',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 34,
    isActive: false,
    code: 'LJA-13-A-000',
    title: 'Corredor 13 Lado A',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 35,
    isActive: false,
    code: 'LJA-13-B-000',
    title: 'Corredor 13 Lado B',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 36,
    isActive: false,
    code: 'LJA-15-A-000',
    title: 'Corredor 15 Lado A',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 37,
    isActive: false,
    code: 'LJA-15-B-000',
    title: 'Corredor 15 Lado B',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 38,
    isActive: false,
    code: 'LJA-17-A-000',
    title: 'Corredor 17 Lado A',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 39,
    isActive: false,
    code: 'LJA-17-B-000',
    title: 'Corredor 17 Lado B',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 40,
    isActive: false,
    code: 'CHS-01-A-000',
    title: 'Checkstand',
    weekday: 5,
    departamentId: '4',
  },
  {
    id: 42,
    isActive: false,
    code: 'LJA-12-A-000',
    title: 'Corredor 12 Lado A',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 43,
    isActive: false,
    code: 'LJA-12-B-000',
    title: 'Corredor 12 Lado B',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 44,
    isActive: false,
    code: 'LJA-14-A-000',
    title: 'Corredor 14 Lado A',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 45,
    isActive: false,
    code: 'LJA-14-B-000',
    title: 'Corredor 14 Lado B',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 46,
    isActive: false,
    code: 'LJA-16-A-000',
    title: 'Corredor 16 Lado A',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 47,
    isActive: false,
    code: 'LJA-16-B-000',
    title: 'Corredor 16 Lado B',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 48,
    isActive: false,
    code: 'LJA-18-A-000',
    title: 'Corredor 18 Lado A',
    weekday: 2,
    departamentId: '5',
  },
  {
    id: 49,
    isActive: false,
    code: 'LJA-20-A-000',
    title: 'Corredor 20 Lado A',
    weekday: 2,
    departamentId: '5',
  },
];

async function seed() {
  for (const departament of departments) {
    const createdDepartament = await prisma.departament.create({
      data: {
        id: departament.id,
        title: departament.title,
        isActive: departament.isActive,
      },
    });

    for (const day of departament.weekdays) {
      await prisma.weekday.create({
        data: {
          day: day,
          departamentId: createdDepartament.id,
        },
      });
    }
  }

  for (const street of streets) {
    await prisma.street.create({
      data: {
        id: street.id,
        code: street.code,
        title: street.title,
        weekday: street.weekday,
        isActive: street.isActive,
        departamentId: Number(street.departamentId),
      },
    });
  }
}

seed().then(() => {
  console.log('Database seeded!');
  prisma.$disconnect();
});
